title: Altos Insights | Be a minimalist everyday.
email: altosinsights@gmail.com
description: O Altos Insights surgiu para que eu possa compartilhar minhas experiências e aprendizados que venho adquirindo ao longo da minha vivência.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://williandutras.github.io" # the base hostname & protocol for your site, e.g. https://example.com
thumb: "/assets/img/thumb.png"
keywords: altosinsights, insights, brenda andrade, brenda, mindset, lifestyle, arte, minimalist, criatividade,
tag_page_layout: tag_page
tag_page_dir: categoria
links:
  - title: home
    url: /
  - title: sobre mim
    url: /sobre-mim
  - title: fale comigo
    url: /fale-comigo

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/
paginate: 4
paginate_path: "/pagina/:num/"


gems:
  - jekyll-feed
  - jekyll/tagging
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
