# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Willian Dutras - HTML5, CSS3, UX Design and Jekyll
email: williandutras15@gmail.com
description: "Me chamo Willian Dutras e meu grande foco é o Front-End, hoje me aventuro no mundo do empreendedorismo com minha startup Pear Coffee."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://williandutras.com" # the base hostname & protocol for your site
twitter_username: williandutrass
thumb: "https://williandutras/img/thumb.png"

# Build settings
markdown: kramdown
permalink: /:title
#permalink: /:categories/:year/:month/:day/:title
